
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyLogin
{

using System;
    using System.Collections.Generic;
    
public partial class Entrega
{

    public int Id { get; set; }

    public string DireccionOrigen { get; set; }

    public Nullable<int> UbicacionOrigen { get; set; }

    public string Producto { get; set; }

    public string Descripcion { get; set; }

    public string Peso { get; set; }

    public string DireccionDestino { get; set; }

    public Nullable<int> UbicacionDestino { get; set; }

    public Nullable<int> Cliente { get; set; }

    public Nullable<int> Pago { get; set; }



    public virtual Cliente Cliente1 { get; set; }

    public virtual Destino Destino { get; set; }

    public virtual Origen Origen { get; set; }

    public virtual Pago Pago1 { get; set; }

}

}
