//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public int servicioID { get; set; }
        public string Nombre { get; set; }
        public string Descripion { get; set; }
        public string Precio { get; set; }
        public string Fecha { get; set; }
        public Nullable<int> IDaccesorio { get; set; }
        public Nullable<int> IDmedicamento { get; set; }
        public Nullable<int> IDmascota { get; set; }
    
        public virtual Accesorio Accesorio { get; set; }
        public virtual Mascota Mascota { get; set; }
        public virtual Medicamento Medicamento { get; set; }
    }
}
